---
book_repo: pivotal-cf/docs-book-windows
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'master'

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

- repository:
    name: pivotal-cf/docs-pcf-windows
    at_path: docs-content
    ref: '2.8'
  directory: platform/application-service-windows/2-8
  subnav_template: windows-subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 2.9
    local_header_img: /images/cloud_rings.png
    local_header_title: PAS for Windows
    search_placeholder: Search PAS for Windows
    url_prefix: platform/application-service-windows/2-8
    changelog_href: https://docs.pivotal.io/platform/2-8/release-notes/windows-rn.html
    local_product_version: 2.8
    local_header_links: []
    local_header_version_list:
      - url_prefix: https://docs.pivotal.io/platform/application-service-windows/2-8
        display_name: v2.9
      - url_prefix: https://docs.pivotal.io/platform/application-service-windows/2-7
        display_name: v2.7
      - url_prefix: https://docs.pivotal.io/pivotalcf/2-6/windows
        display_name: v2.6
      - url_prefix: https://docs.pivotal.io/pivotalcf/2-5/windows
        display_name: v2.5
      - url_prefix: https://docs.pivotal.io/pivotalcf/2-4/windows
        display_name: v2.4
      - url_prefix: https://docs.pivotal.io/pivotalcf/2-3/windows
        display_name: v2.3
      - url_prefix: https://docs.pivotal.io/pivotalcf/2-2/windows
        display_name: v2.2
      - url_prefix: https://docs.pivotal.io/pivotalcf/2-1/windows
        display_name: v2.1
      - url_prefix: https://docs.pivotal.io/pivotalcf/2-0/windows
        display_name: v2.0
