---
template_variables:
  book_title: VMware Tanzu Documentation
  book_title_short: VMware Tanzu Docs
  title: <span class="title-deemph">VMware Tanzu</span> Documentation
  hero_text: "Detailed documentation to help you install, understand, and succeed with VMware Tanzu enterprise-grade software."
  product_url: https://network.pivotal.io/products/pivotal-cf
  product_link: <div class="header-item"><a href="https://network.pivotal.io/products/pivotal-cf">Back to Product Page</a></div>
  support_link: <a href="http://support.pivotal.io" target="_blank">Support</a>
  support_call_to_action: <a href="http://support.pivotal.io" target="_blank">Need Support?</a>
  support_url: http://support.pivotal.io
  use_global_header: true
  global_header_product_href: https://network.pivotal.io/
  global_header_product_link_text: Downloads
  gtm_account_id: GTM-MW4LZHR
  product_network: VMware Tanzu Network
  current_major_version: 2.10
  v_major_version: v2.10

  # Tanzu product variables
  platform_name: Ops Manager
  platform_old: Pivotal Cloud Foundry
  platform_code: PCF
  product_name_lc: pcf
  app_runtime_full: VMware Tanzu Application Service for VMs
  app_runtime_abbr: TAS for VMs
  app_runtime_abbr_lc: tas
  segment_runtime_full: Isolation Segment
  k8s_runtime_full: Tanzu Kubernetes Grid Integrated Edition
  k8s_runtime_abbr: TKGI
  windows_runtime_full: VMware Tanzu Application Service for VMs &#91;Windows&#93;
  windows_runtime_abbr: TAS for VMs &#91;Windows&#93;
  ops_manager_full: Ops Manager
  ops_manager: Ops Manager
  company_name: VMware

# Deprecated variables (use new variables whenever possible)
  product_name: Pivotal Platform
  product_windows_full: Pivotal Application Service for Windows
  product_windows: PASW
  product_runtime: Pivotal Application Service
  product_short: PAS

# Book content variables
